version: '3.8'

services:
  proxy:
    build:
      context: .
    environment:
      PROXY_TO: ${PROXY_TO}
      REPLACED_ORIGIN: ${REPLACED_ORIGIN}
    expose:
      - "${HOST_PORT}"
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
