version: '3.8'

services:
  proxy:
    build:
      context: .
    environment:
      PROXY_TO: ${PROXY_TO}
      ORIGIN: ${ORIGIN}
      REPLACED_ORIGIN: ${REPLACED_ORIGIN}
    ports:
      - "${HOST_PORT}:80"
